### ISSUE TITLE
RPC errors are not handled correctly

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/xhal#150] opened 2020-04-01 21:31 UTC
## Brief summary of issue

xhal doesn't correctly handle the RPC errors:
after an error reported by utils::readReg(reg_name) xdaq process crashed with:

/opt/xdaq/bin/xdaq.exe: symbol lookup error: /home/mdalchen/cms-gem-daq-project/cmsgemos/gemhardware/devices/lib/linux/x86_64_centos7/libgemhwdevices.so: undefined symbol: _ZN4xhal6common3rpc6helper20readExceptionMessageERKN4wisc6RPCMsgE
or, human-readable 

echo _ZN4xhal6common3rpc6helper20readExceptionMessageERKN4wisc6RPCMsgE | c++filt
xhal::common::rpc::helper::readExceptionMessage(wisc::RPCMsg const&)
### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Should correctly intercept the exception 
## Current Behavior

Crashing
## Your Environment

* Version used: latest `develop`
* Shell used:

**Comment by lpetre-ulb** [comment] 2020-04-01 21:43
The issue is certainly due to `xhal-client` library not being linked against the `xhal-base` library. While waiting for the mono-repo, the temporary workaround is to explicitly link against `xhal-base` wherever `xhal-client` is used.

**Comment by jsturdy** [comment] 2020-04-02 14:02
why wasn't `xhal-client` linked against `xhal-base?

**Comment by lpetre-ulb** [comment] 2020-04-03 07:09
Indeed, after reviewing the libraries organization, it looks like the linkage between `xhal-client` and `xhal-base` is not technically necessary. This is counter-intuitive, but, more importantly, the `call.h` header shouldn't be in `common`/`xhal-base` since this header cannot be used from the server. Therefore, it should be in `client`/`xhal-client`.

**Comment by lpetre-ulb** [comment] 2020-05-18 07:10
Fixed in the new repository.

**Closed as completed by lpetre-ulb** 2020-05-18 07:10 UTC
Labels: Type: Bug, Priority: Critical
